##################################################################################
# This compose file deploys the backend and frontend independently.              #
##################################################################################

services:
  frontend:
    build:
      context: ./frontend/
      dockerfile: dockerfile
      target: development
    restart: on-failure
    ports:
      - "4000:4000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - openctf_network
  backend:
    build:
      context: ./backend/
      dockerfile: dockerfile
      target: development
    ports:
      - "8000:8000"
    networks:
      - openctf_network
    volumes:
      - ./backend:/app
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env.dev

networks:
  openctf_network:
    driver: bridge