FROM python:3.12-slim AS base

WORKDIR /app
COPY requirements.txt .

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt

COPY . .

FROM base AS development
ENV FASTAPI_ENV=development
CMD ["python", "server.py"]